/**
 * Nanopub WASM Module for nanopub-create
 * Handles WASM initialization with embedded binary
 * 
 * This module wraps @nanopub/sign to use embedded WASM instead of
 * relying on bundler handling, which fixes esbuild corruption issues.
 */

// Import the web target (not bundler!) from @nanopub/sign
import init, { 
  Nanopub as WasmNanopub, 
  NpProfile as WasmNpProfile,
  KeyPair as WasmKeyPair 
} from '@nanopub/sign/web.js';

// Import embedded WASM data (generated by embed-wasm.js script)
import { NANOPUB_WASM_BASE64, decodeBase64ToBuffer } from './nanopub-wasm.js';

let initialized = false;
let initPromise = null;

/**
 * Initialize the Nanopub WASM module
 * This must be called before using any Nanopub functionality.
 * Safe to call multiple times - will only initialize once.
 * 
 * @returns {Promise<void>} Promise that resolves when WASM is initialized
 * @throws {Error} if initialization fails
 */
export async function initializeNanopub() {
  // Return existing promise if initialization is in progress
  if (initPromise) {
    return initPromise;
  }

  // Skip if already initialized
  if (initialized) {
    return Promise.resolve();
  }

  initPromise = (async () => {
    try {
      console.log('🔄 Initializing Nanopub WASM...');
      
      // Decode embedded WASM from base64
      const wasmBuffer = decodeBase64ToBuffer(NANOPUB_WASM_BASE64);
      console.log(`📦 WASM buffer size: ${(wasmBuffer.byteLength / 1024 / 1024).toFixed(2)} MB`);
      
      // Initialize WASM with the decoded buffer - use object parameter
      await init();
      
      initialized = true;
      console.log('✅ Nanopub WASM initialized successfully');
    } catch (error) {
      console.error('❌ Failed to initialize Nanopub WASM:', error);
      initPromise = null; // Allow retry
      throw new Error(`Nanopub initialization failed: ${error.message}`);
    }
  })();

  return initPromise;
}

/**
 * Check if Nanopub WASM is initialized
 * @returns {boolean} true if initialized, false otherwise
 */
export function isInitialized() {
  return initialized;
}

// Re-export the WASM classes with original names for compatibility
export const Nanopub = WasmNanopub;
export const NpProfile = WasmNpProfile;
export const KeyPair = WasmKeyPair;

// Also provide default export
export default {
  initializeNanopub,
  isInitialized,
  Nanopub,
  NpProfile,
  KeyPair
};
