#!/usr/bin/env node

/**
 * Embed WASM Script for nanopub-create (ES Module version)
 * 
 * This script reads the @nanopub/sign WASM binary and embeds it as base64
 * into a JavaScript module. This allows bundlers to include everything without
 * corrupting the WASM binary.
 * 
 * Run before building: node scripts/embed-wasm.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const WASM_SOURCE = path.join(__dirname, '../node_modules/@nanopub/sign/web_bg.wasm');
const OUTPUT_FILE = path.join(__dirname, '../src/core/nanopub-wasm.js');

function embedWasm() {
  console.log('🔧 Embedding WASM binary...');
  
  // Check if source exists
  if (!fs.existsSync(WASM_SOURCE)) {
    console.error(`❌ ERROR: WASM file not found at ${WASM_SOURCE}`);
    console.error('Make sure @nanopub/sign is installed: npm install @nanopub/sign');
    process.exit(1);
  }

  // Read WASM binary
  const wasmBuffer = fs.readFileSync(WASM_SOURCE);
  console.log(`📦 WASM file size: ${(wasmBuffer.length / 1024 / 1024).toFixed(2)} MB`);
  
  // Convert to base64
  const wasmBase64 = wasmBuffer.toString('base64');
  console.log(`📝 Base64 size: ${(wasmBase64.length / 1024 / 1024).toFixed(2)} MB`);

  // Generate JavaScript module
  const output = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/embed-wasm.js
 * 
 * This file contains the @nanopub/sign WASM binary embedded as base64.
 * This allows bundlers to include everything without corrupting the WASM binary.
 */

/**
 * Base64-encoded WASM binary for @nanopub/sign
 * Source: @nanopub/sign/web_bg.wasm
 * Size: ${(wasmBuffer.length / 1024 / 1024).toFixed(2)} MB
 */
export const NANOPUB_WASM_BASE64 = '${wasmBase64}';

/**
 * Decode base64 string to ArrayBuffer for WASM initialization
 * @param {string} base64 - Base64-encoded WASM binary
 * @returns {ArrayBuffer} ArrayBuffer containing decoded WASM binary
 */
export function decodeBase64ToBuffer(base64) {
  // Use atob for browser environment
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  
  return bytes.buffer;
}
`;

  // Write output
  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`✅ WASM embedded successfully: ${OUTPUT_FILE}`);
  console.log('📂 Generated file size:', (Buffer.from(output).length / 1024 / 1024).toFixed(2), 'MB');
}

// Run if called directly
embedWasm();
